#!/usr/bin/env python3
"""Writes docs/CANDIDATES.md (districts, winners, PR seats, national review)
from data/election/2026/{candidates,results,election,parties}.json."""
import json
import os
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EL = os.path.join(ROOT, "data", "election", "2026")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import jp_names  # noqa: E402


def load(name):
    return json.load(open(os.path.join(EL, name), encoding="utf-8"))


def main():
    cands, results, election, parties = (load(n) for n in
                                         ("candidates.json", "results.json", "election.json", "parties.json"))
    pname = {p["code"]: p["short_ja"] for p in parties["parties"]}
    out = []
    w = out.append
    w("# 第51回衆議院議員総選挙（2026年2月8日）— 候補者・結果一覧")
    w("")
    w("Generated by `tools/gen_candidates_md.py` from the official MIC (総務省) data in `data/election/2026/`. "
      "Vote counts are the official per-candidate totals summed over counting units (fractional 按分票 rounded).")
    w("")
    smd_seats = defaultdict(int)
    pr_seats = defaultdict(int)
    rows_by_pref = defaultdict(list)
    for race in cands["races"]:
        if race["kind"] == "smd":
            tot = defaultdict(int)
            for t in results["races"][race["id"]]["regions"].values():
                for cid, v in t["votes"].items():
                    tot[cid] += v
            ranked = sorted(race["candidates"], key=lambda c: -tot[c["id"]])
            win, run = ranked[0], ranked[1] if len(ranked) > 1 else None
            smd_seats[win["party"]] += 1
            rows_by_pref[race["pref"]].append((race, win, run, tot))
        else:
            for c in race["candidates"]:
                pr_seats[c["party"]] += c["seats_won"] or 0
    w("## 議席 / Seats")
    w("")
    w("| 党派 | 小選挙区 | 比例代表 | 合計 |")
    w("|---|---:|---:|---:|")
    for code in sorted(set(smd_seats) | set(pr_seats), key=lambda k: -(smd_seats[k] + pr_seats[k])):
        w(f"| {pname.get(code, code)} | {smd_seats[code]} | {pr_seats[code]} | {smd_seats[code] + pr_seats[code]} |")
    w(f"| **計** | **{sum(smd_seats.values())}** | **{sum(pr_seats.values())}** | "
      f"**{sum(smd_seats.values()) + sum(pr_seats.values())}** |")
    w("")
    w("## 小選挙区 / Single-member districts (289)")
    for pc in sorted(rows_by_pref):
        w("")
        w(f"### {jp_names.PREF_BY_CODE[pc]['ja']} / {jp_names.PREF_BY_CODE[pc]['en']}")
        w("")
        w("| 選挙区 | 当選 | 党派 | 得票 | 次点 | 党派 | 得票 | 候補者数 |")
        w("|---|---|---|---:|---|---|---:|---:|")
        for race, win, run, tot in rows_by_pref[pc]:
            rv = (f"{run['name_ja']}{' (比例復活)' if run.get('pr_elected') else ''} | {pname.get(run['party'], run['party'])}"
                  f" | {tot[run['id']]:,}") if run else "— | — | —"
            w(f"| {race['name_ja']} | {win['name_ja']} ({win['name_en']}) | {pname.get(win['party'], win['party'])} | "
              f"{tot[win['id']]:,} | {rv} | {len(race['candidates'])} |")
    w("")
    w("## 比例代表 / Proportional representation (176)")
    for race in cands["races"]:
        if race["kind"] != "pr":
            continue
        w("")
        w(f"### {race['name_ja']} / {race['name_en']} ({race['seats']})")
        w("")
        tot = defaultdict(int)
        for t in results["races"][race["id"]]["regions"].values():
            for cid, v in t["votes"].items():
                tot[cid] += v
        w("| 党派 | 得票 | 議席 | 当選者（当選順） |")
        w("|---|---:|---:|---|")
        for c in sorted(race["candidates"], key=lambda c: -tot[c["id"]]):
            elected = sorted((e for e in c["list"] if e["order"] is not None), key=lambda e: e["order"])
            names = "、".join(e["name_ja"] + ("*" if e.get("smd") else "") for e in elected)
            w(f"| {c['name_ja']} | {tot[c['id']]:,} | {c['seats_won'] or 0} | {names} |")
    w("")
    w("\\* 重複立候補者（小選挙区で落選し比例で当選＝比例復活）")
    w("")
    w("## 最高裁判所裁判官国民審査 / Supreme Court national review")
    w("")
    w("| 裁判官 | 罷免を可とする | 罷免を可としない | 罷免可の割合 | 結果 |")
    w("|---|---:|---:|---:|---|")
    for ref in election["referendums"]:
        regs = results["referendums"][ref["id"]]["regions"].values()
        a = sum(r["agree"] for r in regs)
        d = sum(r["disagree"] for r in regs)
        w(f"| {ref['justice_ja']} ({ref['justice_en']}) | {a:,} | {d:,} | {100 * a / (a + d):.2f}% | "
          f"{'罷免' if a > d else '信任'} |")
    w("")
    w("Sources: " + ", ".join(f"[{s['title']}]({s['url']})" for s in election["sources"]))
    os.makedirs(os.path.join(ROOT, "docs"), exist_ok=True)
    with open(os.path.join(ROOT, "docs", "CANDIDATES.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote docs/CANDIDATES.md")


if __name__ == "__main__":
    main()
